source: sitesource

theme: minimal-mistakes-jekyll

include: ["_pages", "assets"]

title: "Azur Lane EN PVP Guide"

minimal_mistakes_skin: "air"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
